### ISSUE TITLE
fetch support for ADD JAR queries

### ISSUE THREAD

**Issue by kaschaeffer** [forward3d/rbhive#13]
I'm using rbhive on HiveServer2 to execute arbitrary commands and, if there is a response, to capture that.  The fetch command works generally quite well.  However, it seems to not support "ADD JAR ..." type commands for loading UDFs.  

I can alternatively use the execute command.  However, this has the disadvantage of not loading results in a simple way and of suppressing _all_ errors.

Is there a way to modify fetch so that it supports arbitrary queries?

Thanks,
Kevin

**Comment by khanh-nguyen** [comment]
@andytinycat I got this issue with cdh5
```ruby
options = { :transport => :buffered, :hive_version => :cdh5, :transport => :sasl, :sasl_params => {}}
RBHive.tcli_connect("hive-server-address", 10000, options) do |connection|
    connection.execute("ADD JAR /nfs/shared/path/to/myjar.jar")
    ...
end
```
The error I got is 
```
RBHive::TCLIConnectionError:
       Error while processing statement: /nfs/shared/path/to/myjar.jar does not exist
```
I could go to the server and verify that the file exists: `ls -l /nfs/shared/path/to/myjar.jar`.
Do you have any idea why?
