### ISSUE TITLE
Max Rows in Fetch

### ISSUE THREAD

**Issue by rafer** [forward3d/rbhive#43]
Hello!

First off, thank you very much for your hard work on this project!

I recently was surprised by the default of max_rows = 100 [here](https://github.com/forward3d/rbhive/blob/master/lib/rbhive/t_c_l_i_connection.rb#L319), so I thought I'd ask if there was a reason that it wouldn't make sense to effectively default max_rows to +Infinity? Would changing that involve significant technical hurdles?

Thanks!

**Comment by rafer** [comment]
Also, I noticed [fetch_in_batch](https://github.com/forward3d/rbhive/blob/master/lib/rbhive/t_c_l_i_connection.rb#L333) which appears to allow for unlimited number of returned results. The only issue is that it requires the user to supply a block. I think this could be fairly easily wrapped in an enumerable object. Let me know if you think that might be worth investigating or if you'd like met to take a crack at implementing.

**Comment by lloydpick** [comment]
The default max rows of 100 is effectively to stop you consuming all the memory of your machine while receiving rows back from Hive. At that point you should use fetch_in_batch so that you're dealing with a known number of rows at any one time, rather than infinity.

**Comment by rafer** [comment]
I'm wondering if defaulting `max_rows` to 100 (or any number, really) flies somewhat in the face of what a user might expect from a data retrieval tool. As support for this statement I would submit that  neither the [`#fetch`](http://sequel.jeremyevans.net/rdoc/classes/Sequel/Database.html#method-i-fetch)  method in [Sequel](https://github.com/jeremyevans/sequel) nor the `Model.all` method in ActiveRecord default to a max result size. If you execute one of these methods on a table with a billion rows, your machine will indeed run out of memory. Similarly, if you `ls` a directory with 10K files in it, it will return all 10K files :smiley: 

Anyway, if you think it makes sense to keep a non-infinite `max_rows` default, I'd suggest mentioning it in the readme. If you decide to go this way, I'd be glad to submit a PR for the doc change.

Thanks again!

**Comment by lloydpick** [comment]
I must admit it does usually cause issues. I've just looked at removing that restriction, but it seems no matter what, you must specify a max rows for Thrift to return as you can see here https://github.com/forward3d/rbhive/blob/master/lib/thrift/t_c_l_i_service_types.rb#L1607. The other option is to just make `fetch` call `fetch_in_batch` internally.
